spring:
  application:
    name: tika-pipes
grpc:
  server:
    numThreads: 4
    port: 9090
    max-inbound-message-size: 104857600 # 100MB
    max-outbound-message-size: 104857600 # 100MB
    health:
      enabled: false
ignite:
  workDir: 'ignite/work'
  persistence:
    enabled: true
  memory:
    default:
      size: 1G
  sql:
    log: debug
forkparser:
  pool:
    core-size: 5
    max-size: 10
    queue-capacity: 100
