spring:
  application:
    name: tika-pipes
grpc:
  server:
    port: 9090
ignite:
  workDir: 'ignite/work'
  persistence:
    enabled: true
  memory:
    default:
      size: 1G
  sql:
    log: debug
